
name: release

on:
  push:
    branches:
      release-testing
    tags:
    - '[0-9]+'

jobs:
  dist-x86_64-unknown-linux-gnu:
    name: dist (x86_64-unknown-linux-gnu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Build
        run: cargo build --release
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-unknown-linux-gnu
          path: target/release/sysroot-creator
